### PR TITLE
chore: migrate to @chainsafe/is-ip

### PR DESCRIPTION
**Pull request by tuyennhv**
**Motivation**
- ~is-ip 4.0.0 is the last performant version of is-ip (version 5.0.0 has a performance issue)~
- use @chainsafe/is-ip which is significantly faster

**Description**
~Migrate to is-ip 4.0.0~
Migrate to `@chainsafe/is-ip`

### CODE REVIEW

**Comment by wemeetagain** [comment]
@tuyennhv can you use `@chainsafe/is-ip` v2.0.1?

**Comment by tuyennhv** [comment]
migrated to `@chainsafe/is-ip` as it's significantly faster, see https://github.com/ChainSafe/is-ip/pull/1

**Comment by frenchbread** [comment]
Thanks @tuyennhv & @wemeetagain!

`@chainsafe/is-ip` appears to be an ESM module which `private-ip` does not support at this point. Would you mind converting this package to `esm` package? (reference [`pure ESM`](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c))

**Comment by frenchbread** [comment]
Great work, thanks!

**Pull request merged**
